### ISSUE TITLE
Leaking cluster data in state

### ISSUE THREAD

**Issue by WoLfulus** [pulumi/pulumi-digitalocean#141]
The `kubeConfigs` key in the output of a `KubernetesCluster` resource is getting stored as plain text. Both rawConfig and token.

![image](https://user-images.githubusercontent.com/412397/94725955-f050b000-0332-11eb-970b-1a031b4898b3.png)

**Comment by lukehoban** [comment]
Today you can address this by adding `additionalSecretOutputs`.  See https://www.pulumi.com/docs/intro/concepts/programming-model/#additionalsecretoutputs. 

With https://github.com/pulumi/pulumi-terraform-bridge/issues/10 this should ideally be done automatically without the need for manual annotation. 

We may also be able to special case these ahead of fully addressing that issue - though  we’d like to make this change broadly if possible - and I believe are planning to tackle that broader issue soon.

**Comment by WoLfulus** [comment]
This isn't my outputs though. It's on the output of a resource?

**Comment by stack72** [comment]
@lukehoban / @infin8x circling back here, so this isn't actually set as sensitive upstream - I am going to suggest we handle this as a sensitive value in the pulumi schema - does this seem sensible to you both?

**Comment by infin8x** [comment]
@stack72 makes sense to me!

**Comment by stack72** [comment]
Ok, I take that back - this would have been fixed as part of v3.4.0 release
