### ISSUE TITLE
Obtaining list of ssh keys

### ISSUE THREAD

**Issue by wrbbz** [pulumi/pulumi-digitalocean#152]
Hello!

Is it possible to obtain a list of ssh keys?
Or will it be possible in the future?

Right now I'm doing it with `dogo` library. But it would be nice to retrieve a list with `pulumi`

I suppose, the absence of this feature is caused by its absence in terraform provider. 
Nevertheless, it has no use with HCL (IMHO), but could be used with languages that has loops functionality.

Maybe i can help you with something. Just let me know

**Comment by stack72** [comment]
Hey all

I just opened https://github.com/digitalocean/terraform-provider-digitalocean/pull/519 upstream to get this new functionality

When this is merged, Pulumi will be able to take advantage of the schema is generates

Paul

**Comment by wrbbz** [comment]
Thank you!

Looking forward to see this functionality in `pulumi`
