### ISSUE TITLE
`pulumi destroy` fails due to dependency between droplet and volume attachment

### ISSUE THREAD

**Issue by anentropic** [pulumi/pulumi-digitalocean#158]
I have a basic stack with:

- an ssh key
- 1 droplet
- 1 volume
- a "volume attachment" of volume->droplet
- a domain
- some dns records

I guess Pulumi is destroying things in reverse dependency order (vol attach -> vol -> droplet), or arbitrary?

If I do `pulumi destroy` it fails because DO won't let you delete the volume attachment while the droplet is powered up.

There is a dedicated API for destroying droplet + associated resources which might be useful:  
https://developers.digitalocean.com/documentation/v2/#selectively-destroy-a-droplet-and-its-associated-resources

Otherwise Pulumi might need its own rule to know to destroy the droplet first (haven't tried it, I guess that works)

**Comment by anentropic** [comment]
Hmm... it failed last time I did it, with an error from DO:
```
Error deleting volume: DELETE https://api.digitalocean.com/v2/volumes/220d49d3-26cd-11eb-ae75-0a58ac14c19b: 409 (request "9e88558d-1159-45d6-8890-c44d47e29e4c") failed to delete volume: attached volume cannot be deleted
```

But succeeded this time, first deleting the Vol Attachment, then the Volume then the Droplet.

I'll close this for now in case it doesn't happen again

**Comment by anentropic** [comment]
Getting this again...

first attempt says:
```
  digitalocean:index:VolumeAttachment (pgb-dokku-db-vol-attachment):
    error: 1 error occurred:
    	* Error attaching volume to droplet after retry timeout: [WARN] Error attaching volume (08c4e420-2732-11eb-b21d-0a58ac14c0da) to Droplet (218074863): POST https://api.digitalocean.com/v2/volumes/08c4e420-2732-11eb-b21d-0a58ac14c0da/actions: 422 (request "f73c9f7e-4c74-423f-8c81-a7a537bc0852") error attaching volume to droplet: storage already associated with another droplet
```
immediately retrying another `pulumi up --refresh` I get:
```
  digitalocean:index:VolumeAttachment (pgb-dokku-db-vol-attachment):
    error: deleting urn:pulumi:staging::myproject.com::digitalocean:index/volumeAttachment:VolumeAttachment::pgb-dokku-db-vol-attachment: 1 error occurred:
    	* Error detaching volume from droplet after retry timeout: [WARN] Error detaching volume (08c4e420-2732-11eb-b21d-0a58ac14c0da) from Droplet (218070860): POST https://api.digitalocean.com/v2/volumes/08c4e420-2732-11eb-b21d-0a58ac14c0da/actions: 422 (request "4e234716-af0a-4ace-8cd3-d66db3fe5d44") invalid volume id: invalid region name
```
a third time, first error again:
```
  digitalocean:index:VolumeAttachment (pgb-dokku-db-vol-attachment):
    error: 1 error occurred:
    	* Error attaching volume to droplet after retry timeout: [WARN] Error attaching volume (08c4e420-2732-11eb-b21d-0a58ac14c0da) to Droplet (218075660): POST https://api.digitalocean.com/v2/volumes/08c4e420-2732-11eb-b21d-0a58ac14c0da/actions: 422 (request "f64bbcef-a784-48e9-8057-7cd83d63498c") error attaching volume to droplet: storage already associated with another droplet
```

I tried adding `delete_before_replace=True` to the VolumeAttachment and tried again:
```
  digitalocean:index:VolumeAttachment (pgb-dokku-db-vol-attachment):
    error: deleting urn:pulumi:staging::myproject.com::digitalocean:index/volumeAttachment:VolumeAttachment::pgb-dokku-db-vol-attachment: 1 error occurred:
    	* Error detaching volume from droplet after retry timeout: [WARN] Error detaching volume (08c4e420-2732-11eb-b21d-0a58ac14c0da) from Droplet (218075212): POST https://api.digitalocean.com/v2/volumes/08c4e420-2732-11eb-b21d-0a58ac14c0da/actions: 422 (request "1fa57a7b-5326-4a25-b1e0-60c9093fdf7c") invalid volume id: invalid region name
```

but maybe it's just alternating between these two error states

**Comment by anentropic** [comment]
a `pulumi destroy` worked though

**Comment by leezen** [comment]
Could you please provide the program you're using?

**Comment by anentropic** [comment]
```python
import chevron
import pulumi
import pulumi_digitalocean as do


def file_contents(path: str) -> str:
    with open(path, "r") as f:
        return f.read()


def render_template(path: str, context: dict) -> str:
    with open(path, "r") as f:
        return chevron.render(f, context)


conf = pulumi.Config()
APPS_DOMAIN = conf.require("apps-domain")
PGB_APP_NAME = conf.require("pgb-app-name")
SSH_KEY_PATH = conf.require("ssh-key-path")


ssh_key = do.SshKey(
    "pgb-dokku-ssh-key",
    public_key=file_contents(SSH_KEY_PATH),
    name="pulumi-digitalocean-ecdsa",
)

db_vol = do.Volume(
    "pgb-db-vol",
    region="lon1",
    size=1,  # GB
    initial_filesystem_type="ext4",
    description="Block storage for our SQLite db",
    initial_filesystem_label="database",
)
pulumi.export("db-vol-name", db_vol.name)

# path in droplet: `/mnt/<db-vol-name>`
db_volume_path = db_vol.name.apply(lambda val: "/mnt/{}".format(val.replace("-", "_")))
pulumi.export("droplet-db-vol-mount", db_volume_path)

# for possible image/region/size slug values see https://slugs.do-api.dev/
droplet = do.Droplet(
    "pgb-dokku-droplet",
    image="dokku-20-04",
    region="lon1",
    size="s-1vcpu-1gb",
    monitoring=True,
    ssh_keys=[ssh_key.id],
    user_data=render_template(
        "./pgb-dokku-userdata.sh.tpl",
        {
            "apps_domain": APPS_DOMAIN,
            "pgb_app_name": PGB_APP_NAME,
            "db_volume_path": db_volume_path,
            "ssh_key_name": ssh_key.name.apply(lambda val: val),
        },
    ),
)
pulumi.export("droplet-ip", droplet.ipv4_address)


do.VolumeAttachment(
    "pgb-dokku-db-vol-attachment",
    droplet_id=droplet.id.apply(lambda val: int(val)),
    volume_id=db_vol.id,
)


domain = do.Domain(
    "pgb-domain",
    pulumi.ResourceOptions(
        delete_before_replace=True,  # required for DO domains (no update endpoint)
    ),
    name=APPS_DOMAIN,
    ip_address=droplet.ipv4_address,  # will also create an A record
)
for i in range(1, 4):
    do.DnsRecord(
        f"pgb-domain-ns-{i}",
        domain=domain.name,
        type="NS",
        value=f"ns{i}.digitalocean.com.",
        name="@",
    )

do.DnsRecord(
    "pgb-domain-cname-*",
    domain=domain.name,
    type="CNAME",
    name="*.",
    value=f"{APPS_DOMAIN}.",
)
```

**Comment by anentropic** [comment]
an update on the `pulumi destroy`...

it seems the previous failed `up` means it mistakenly believed that some resources no longer existed...

`pulumi destroy` showed:
```
     Type                           Name                     Plan
 -   pulumi:pulumi:Stack            myproject.com-staging  delete
 -   ├─ digitalocean:index:Droplet  pgb-dokku-droplet        delete
 -   ├─ digitalocean:index:SshKey   pgb-dokku-ssh-key        delete
 -   └─ digitalocean:index:Volume   pgb-db-vol               delete

Outputs:
  - db-vol-name         : "pgb-db-vol-13203c3"
  - droplet-db-vol-mount: "/mnt/pgb_db_vol_13203c3"
  - droplet-ip          : "143.110.168.46"

Resources:
    - 5 to delete
```
Note it says "5 to delete" under Resources but only three are listed in the table above (plus the abstraction of the stack itself)

So the Domain resource got left behind, no longer tracked by Pulumi... now when I go to do an `up` from scratch I get:
```
* Error creating Domain: POST https://api.digitalocean.com/v2/domains: 422 domain 'myproject.com': name already exists
```

I would have thought, in a "desired state" model, finding that the resource you need to create already exists would be a success, and if it doesn't match the desired properties then update/delete+recreate it.

But here Pulumi is just seeing an error and doesn't learn anything.

Can I get Pulumi to recognise that the Domain already exists?

Apparently not... if I do `pulumi refresh` it only refreshes state of the items it knows to exist (the ones created by the previous  `up` which did not complete):
```
     Type                                    Name                         Plan
     pulumi:pulumi:Stack                     myproject.com-staging
     ├─ digitalocean:index:Volume            pgb-db-vol
     ├─ digitalocean:index:SshKey            pgb-dokku-ssh-key
     ├─ digitalocean:index:VolumeAttachment  pgb-dokku-db-vol-attachment
     └─ digitalocean:index:Droplet           pgb-dokku-droplet

Resources:
    5 unchanged
```
So I have to fix this manually in DO control panel

**Comment by leezen** [comment]
In terms of your original issue w/ removing the attachment, does this work if you use `volumeIds` on the Droplet resource instead of creating an explicit `VolumeAttachment` resource? https://www.pulumi.com/docs/reference/pkg/digitalocean/droplet/#volumeids_nodejs

**Comment by anentropic** [comment]
I will try that...

**Comment by anentropic** [comment]
Just a general question on the side... is the Pulumi DO provider basically autogenerated from https://github.com/digitalocean/terraform-provider-digitalocean/ ?

Is it likely that some of these issues are problems with the underlying Terraform provider?

**Comment by anentropic** [comment]
I did a clean `pulumi up` using `volume_ids` on the Droplet resource which appeared to complete successfully.

But now it seems to produce spurious diff when I `pulumi refresh`:
```
digitalocean:index:Droplet    pgb-dokku-droplet        replace     [diff: ~userData]
```

If I do an `pulumi up --refresh` it now wants to replace the droplet, which fails due to the original issue:
```
* Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 storage already associated with another droplet
```

**Comment by leezen** [comment]
> Is it likely that some of these issues are problems with the underlying Terraform provider?

Possibly. Though, I have a couple other thoughts on what's going on with your program:

1. Your apply should wrap the render, not the other way around:

```python
user_data=ssh_key.name.apply(lambda val: render_template(
        "./pgb-dokku-userdata.sh.tpl",
        {
            "apps_domain": APPS_DOMAIN,
            "pgb_app_name": PGB_APP_NAME,
            "db_volume_path": db_volume_path,
            "ssh_key_name": val,
        },
    )),
```

This may be part of why your `user_data` is showing a diff since otherwise, it's likely getting the incorrect data that's changing each time (since `ssh_key.name.apply(lambda val: val)` is just an `Output` object that will have a different reference each time that gets converted to a string) whereas you actually want to provide an `Output` object (the return value for an `apply`) to `user_data`.

2. In the case where you do need to replace the `Droplet` and since there's a volume attached, you'll want to specify `delete_before_replace` (https://www.pulumi.com/docs/intro/concepts/programming-model/#deletebeforereplace). Else, the program will attempt to create the replacement first. As a result, when attempting to use the same volume on that create, it'll fail with the error above. In contrast, if you specify `delete_before_replace` the original droplet gets deleted first, which frees up the volume for the replacement droplet.

**Comment by anentropic** [comment]
I realise in my own code I have the `userData` generated dynamically varying on the volume name

but that shouldn't have changed after (apparently successful) creation of both the droplet+volume

**Comment by anentropic** [comment]
ah I see!

**Comment by anentropic** [comment]
thanks very much for your help

with the fix to the `user_data` rendering and a `delete_before_replace` on the Droplet it seems stable now (and able to successfully recreate the droplet)

**Comment by leezen** [comment]
Awesome. Glad to hear it's all working for you. I'll close this issue, but feel free to comment if you feel there are still outstanding problems that require a look.
