### ISSUE TITLE
pulumi up --refresh fails on replacing domain

### ISSUE THREAD

**Issue by anentropic** [pulumi/pulumi-digitalocean#166]
```
+-  ├─ digitalocean:index:Domain            pgb-domain                   **replacing failed**     [diff: ~ipAddress]; 1 error
```
```
  digitalocean:index:Domain (pgb-domain):
    error: 1 error occurred:
    	* Error creating Domain: POST https://api.digitalocean.com/v2/domains: 422 domain 'myproject.com': name already exists
```
is this on me to apply the `deleteBeforeReplace=True` option on DigitlaOcean Domain resources, or should it be the default?

**Comment by stack72** [comment]
Hi @anentropic 

My apologies this has gotten you here. On *most* of our resources, Pulumi has autonaming enabled - it doesn't make sense to do that on Domain names so this would require a specific deleteBeforeCreate operation

Paul

**Comment by anentropic** [comment]
I can see also the DigitalOcean API lacks an update endpoint for domains, so delete and recreate for an update makes sense
