### ISSUE TITLE
Load Balancer creation sometimes fails with 500 Server Error

### ISSUE THREAD

**Issue by onedr0p** [pulumi/pulumi-digitalocean#190]
## Expected behavior

A Load Balancer to be created

## Current behavior

Load Balancer creation sometimes fails with 500 server error

```
Diagnostics:
  pulumi:pulumi:Stack (home-cluster-ansible-single-control-plane):
    error: update failed

  digitalocean:index:LoadBalancer (http-public):
    error: 1 error occurred:
    	* Error creating Load Balancer: POST https://api.digitalocean.com/v2/load_balancers: 500 Server Error
```

In the DO documentation it states:

> If you receive a status in the 500 range, this generally indicates a server-side problem. This means that we are having an issue on our end and cannot fulfill your request currently.

It would be nice if Pulumi could retry on HTTP errors...

## Steps to reproduce

1. Try to create 10 Load Balancers
2. destroy them
3. create them again
4. destroy them
5. create them again
6. destroy them
7. Watch it likely fail somewhere in steps 1-5

**Comment by lblackstone** [comment]
The relevant provider code is upstream, so we can't add retry logic for this provider. You might consider using the [Automation API](https://www.pulumi.com/blog/automation-api/) to add your own retry logic in case of failures from this provider.

**Comment by onedr0p** [comment]
I've read thru that documentation but don't see how to write that logic. Are you saying I need to write the logic to make a API request to create the load balancers myself instead of using the built in methods?

I've seen many issues in the Pulumi/Pulumi repo asking for retry support, so if the problem is upstream to you guys that's a bummer.

**Comment by lblackstone** [comment]
> Are you saying I need to write the logic to make a API request to create the load balancers myself instead of using the built in methods provided by this library?

Rather than retrying the LoadBalancer creation, you could conditionally retry the entire stack update. On the rerun, Pulumi should only have to update the failed resources, so it's a similar result.

>  if the problem is upstream to you guys that's a bummer

Yeah, that's the case for Terraform-based providers, although you can file an issue upstream, and we regularly pull in upstream changes if it gets changed there. Our native providers (currently Kubernetes and Azure) do have retries built in.

**Comment by onedr0p** [comment]
Thank you so much for the details and for finding that issue! I'll keep an eye on it.
