### ISSUE TITLE
AppSpec doesn't support `domain` or `domains` attribute, even though Terraform provider does

### ISSUE THREAD

**Issue by rdjogo** [pulumi/pulumi-digitalocean#191]
https://github.com/digitalocean/terraform-provider-digitalocean/blob/v2.5.1/digitalocean/app_spec.go#L27-L39

The deprecation warning is written out, but there's no support for either of these attributes.

**Comment by stack72** [comment]
Great find @rdjogo 

The issue here is that when we have a set or a list, we pluralise the name so domain -> domains which clashes with domains

So I need to map domain -> domainNames that would allow you to set them as expected 

I'll have this fixed up and re-released tomorrow

Paul

**Comment by rdjogo** [comment]
Awesome, thanks a lot @stack72 !
