### ISSUE TITLE
Support for domainUrn on DO K8s clusters, node pools

### ISSUE THREAD

**Issue by mplewis** [pulumi/pulumi-digitalocean#216]
Hello! I'm looking to organize my DigitalOcean resources into a DO project with Pulumi.

I understand that we create a DO project and manage its child resources by passing domain URNs from various resources into a `Project` like this:

```ts
import * as dio from "@pulumi/digitalocean";

const myDomain = new dio.Domain(
  "my-domain",
  { name: "my-domain.com" },
  { protect: true }
);

new dio.Project(
  "my-project",
  {
    description: "",
    environment: "Production",
    name: "My Project",
    purpose: "Web Application",
    resources: [
      myDomain.domainUrn, 
      // other resource domain URNs go here too
    ]
  },
  { protect: true }
);
```

However, I'm having trouble getting the domain URN for the `digitalocean.KubernetesCluster` and `digitalocean.KubernetesNodePool` as they don't seem to be exposed on those types.

Is it possible to expose these so I can use Pulumi to add my cluster to my DO project? Thank you for taking a look.

**Comment by stack72** [comment]
Hi @mplewis 

I jsut spoke with the DO team about this and they will expose it on their side soon so we should pick it up with the next code update from upstream

Paul
