### ISSUE TITLE
Go module version path does not match the version

### ISSUE THREAD

**Issue by yitsushi** [pulumi/pulumi-digitalocean#235]
New project generated with `v3.3.1` generates a `go.mod` file with `v4` digitalocean sdk, but on `go get` it fails because the module says it's `v3`.

Most likely just a simple update in the go.mod file: https://github.com/pulumi/pulumi-digitalocean/blob/master/sdk/go.mod#L1

```diff
- module github.com/pulumi/pulumi-digitalocean/sdk/v3
+ module github.com/pulumi/pulumi-digitalocean/sdk/v4
```

## Expected behavior
With `pulumi new` I can get an new project that works without issues.

## Current behavior
It does not work because the `v4` module is not there (it's there, but at the same time it's not there; go magic)

### With generate only

1. `mkdir check && cd check`
2. `pulumi new digitalocean-go --name do-k8s-test --generate-only --yes`
3. `go mod download`
4. Error message:
```
go: github.com/pulumi/pulumi-digitalocean/sdk/v4@v4.2.0: sdk/go.mod has non-.../v4 module path "github.com/pulumi/pulumi-digitalocean/sdk/v3" (and .../v4/go.mod does not exist) at revision sdk/v4.2.0
```

### Default logic (not just generate)

1. `mkdir check && cd check`
2. `pulumi new digitalocean-go --name do-k8s-test --yes`
3. Output with error:

```
Created project 'do-k8s-test'
Created stack 'dev'
Installing dependencies...
go: github.com/pulumi/pulumi-digitalocean/sdk/v4@v4.2.0: sdk/go.mod has non-.../v4 module path "github.com/pulumi/pulumi-digitalocean/sdk/v3" (and .../v4/go.mod does not exist) at revision sdk/v4.2.0
error: `go mod download` failed to install dependencies; rerun manually to try again, then run 'pulumi up' to perform an initial deployment: exit status 1
```

## Context (Environment)
* OS: Linux
* Pulumi CLI version: v3.3.1
* Language: Go 1.16

## Affected feature

I don't know, it's seems only a "typo".

**Comment by stack72** [comment]
Closed via https://github.com/pulumi/pulumi-digitalocean/commit/ecf330ba6ac6e68a1adeebab67e46a594daca231

**Comment by stack72** [comment]
Hey @yitsushi 

https://github.com/pulumi/pulumi-digitalocean/actions/runs/886680322

That build will fix it! Thanks again 

Paul

**Comment by yitsushi** [comment]
@stack72: just came back to report, it's working as expected with `v4.3.1`, thank you ;)

**Comment by stack72** [comment]
great news!
