### ISSUE TITLE
C# FirewallArgs.DropletIds Property InputList<int> Droplet.Id Output<string>

### ISSUE THREAD

**Issue by napalm684** [pulumi/pulumi-digitalocean#248]
There appears to be a type mismatch here with the firewall droplet ids wanting int values and droplet exporting strings

## Steps to reproduce
Create a droplet and a firewall, try to pass in `droplet.id` as the `DropletIds` value

Expected:  The value to be accepted.
Actual: Compiler complains of type mismatch

Same issue as TypeScript https://github.com/pulumi/pulumi-digitalocean/issues/81

**Comment by leezen** [comment]
Duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/352
