### ISSUE TITLE
App platform managed database limit

### ISSUE THREAD

**Issue by vladshcherbin** [pulumi/pulumi-digitalocean#249]
I have a stack with 3 databases and a few apps on App platform.
Account already has 5 managed databases and a couple of apps on App platform.

When I'm trying to spin a new deployment, 3 new databases are created successfully but some apps on App platform fail with error:

```
* Error creating App: POST https://api.digitalocean.com/v2/apps: 400 error validating databases field "databases.limit_exceeded": (3) new databases were requested but the account's Managed Database limit only allows for up to (2) new databases
```

Seems like it thinks I'm trying to create a database instead of pointing to existing one. I **have same stack under different name and it didn't have this problem** (due to limit not reached I guess).

What can be the problem? 

_I've asked DO support and they told managed db limit is 10_

## Steps to reproduce

1. Create a stack
2. Add ~8 databases
3. Add ~10 Apps on app platform using this databases
4. Try to deploy

Expected: No error
Actual: Error

<img width="775" alt="Screen Shot 2021-08-02 at 18 49 28" src="https://user-images.githubusercontent.com/6711845/127898383-6b9ba1cb-d7ef-431d-a95e-035f3f78bed8.png">

**Comment by stack72** [comment]
Hi @vladshcherbin 

Please can you give me a sample of code that I can use to try and recreate this issue?

Thanks

Paul

**Comment by vladshcherbin** [comment]
Yep, I'll try to create a sample stack repo during the week

**Comment by stack72** [comment]
thanks so much!!

**Comment by mikhailshilkov** [comment]
Since we haven't heard back, I'll go ahead and close this issue as stale
