### ISSUE TITLE
DnsRecord resource append a randomly generated id to hostnames

### ISSUE THREAD

**Issue by turbobabr** [pulumi/pulumi-digitalocean#275]
I'm trying to create a subdomain using `DnsRecord` resource using the following code:
```ts
import * as pulumi from "@pulumi/pulumi";
import * as digitalocean from "@pulumi/digitalocean";

const domain = new digitalocean.DnsRecord('arv',{
  domain: 'blah-blah.cc',
  type: 'A',
  value: 'x.x.x.x',
  ttl: 300
});
```

I expect to get `arv.blah-blah.cc` record to be created, but instead I get my name altered by `pulumi` that add some sort of id suffix like this:
![image](https://user-images.githubusercontent.com/6356526/143764479-636a6a73-2db6-4347-9781-e8ed6faab3a1.png)

I understand that `pulumi` adds it to guarantee uniqueness of the resource, but what if I want to create a record to be used by people entering the name manually, something like:
- api.blah-blah.cc
- blog.blah-blah.cc
- photos.blah-blah.cc

Is there a way to turn off that suffix completely and make me as a developer responsible for keeping those names unique?

**Comment by stack72** [comment]
Hi @turbobabr 

I'm sorry our documentation doesn't point this out directly but if you pass a "name" parameter to the DnsRecord args then you are able to override the automating

When no name is provided, we actually pass the resource name and the random suffix as the name to the DO record

So all you'd need to do here is add name: "arv"

I hope this helps

Paul

**Comment by turbobabr** [comment]
@stack72 Thank you Paul! Works like a charm! 🙏 

It would be really nice to get some mention regarding this in the docs.

**Comment by stack72** [comment]
I agree with you @turbobabr - I may disable Autonaming for this specific resource
