### ISSUE TITLE
Spaces env vars not mapped to config

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-digitalocean#279]
To create a digitalocean space, you need to set a spaces access key id and secret key. You can do this on the provider like so:

```
pulumi config set digitalocean:spaces_access_id <key>
pulumi config set digitalocean:spaces_secret_key <key> --secret
```

You should _also_ be able to set it using environment variables:

```
export SPACES_ACCES_KEY_ID=key
export SPACES_SECRET_ACCESS_KEY=key
```

However, when using the environment variables only, you get the following error:

```
  digitalocean:index:SpacesBucket (example):
    error: 1 error occurred:
    	* Error creating bucket: Spaces credentials not configured
```

**Comment by ringods** [comment]
Correction. Credentials must be set in config with the provider prefix:

```sh
$ pulumi config set digitalocean:spaces_access_id <key>
$ pulumi config set digitalocean:spaces_secret_key <key> --secret
```

**Comment by jaxxstorm** [comment]
This was user error, if you set the env var's correctly, it works

@ringods thanks for the correction~

**Comment by devicee** [comment]
I can confirm this! Maybe it should be added to the manual as well.
