### ISSUE TITLE
Database port is returned  as int and unable to convert it to sting

### ISSUE THREAD

**Issue by UnP1u9** [pulumi/pulumi-digitalocean#288]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

While creating a Database, the output for the port is int, I want to use that port in Kubernetes configmap which only accepts the str format, I tried multiple ways to convert int to sting but they don't work due to pulumi's output format. is there any way i can change it to str or any workaround to convert int to str in pulumi.

### Steps to reproduce

1. Create a database
2. Extract Database port in variable to use in Configmap (DB_PORT = mysql.port.apply(lambda port: port))
3.  Use same variable in Configmap, "binary_data={"DB_PORT" : DB_PORT } ,"
4. pulumi up will now give bellow error. 

"""
error: resource default/vault-port-gqg1dja7 was not successfully created by the Kubernetes API server : ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.BinaryData: base64Codec: invalid input, error found in #10 byte of ...|"DB_PORT":25060},"ki|..., bigger context ...|{"apiVersion":"v1","binaryData":{"DB_PORT":25060},"kind":"ConfigMap","metadata":{"annotations|
"""

Thanks!!

**Comment by leezen** [comment]
Could you please provide more of your code? Your lambda as written currently is a no-op and I would've expected 

```python
DB_PORT = mysql.port.apply(lambda port: str(port))
```

to actually make it a string.

**Comment by UnP1u9** [comment]
Hey, thanks! this worked for port, no-op with the issue.

but when I use the get_database_ca like 

certificate_new = do.get_database_ca(cluster_id=mysql_cluster.id.apply(lambda id: str(id))).certificate

then I get the below error

Exception: invoke of digitalocean:index/getDatabaseCa:getDatabaseCa failed: Required attribute is not set ()

Thanks!

**Comment by UnP1u9** [comment]
Hey @leezen, it worked like charm, my no-op lamda was the issue, Thanks a ton.
