### ISSUE TITLE
digitalocean kubernetes: kubeconfig and access tokens

### ISSUE THREAD

**Issue by ulrichSchreiner** [pulumi/pulumi-digitalocean#312]
hi,

when creating a kubernetes cluster on digitalocean the pulumi state contains the kubeconfig for the created cluster. this is a problem with digitalocean because they:

  - create a new api token on every download of the kubeconfig
  - expire the token after 7 days

so i have the problem that a `pulumi up` works only within the first seven days. after that a `pulumi up` shows the cluster as not accessible and marks the resources in the cluster as deleted.

when you do a `pulumi refresh` a new DO API token is generated. every refresh generates a new token. after a handful of refreshes you have a handful of api-tokens with DO (and they will all disappear after seven days).

i'm not sure what the solution should look like. but it looks not perfect to store the KUBECONFIG in the state when this kubeconfig will fail after seven days. perhaps you should  explictly retrieve a config with a higher expire-value? or give the user an easy way to refresh/up the stack when the kubeconfig does not work any more.

more info:
https://www.digitalocean.com/community/questions/when-saving-kubernetes-config-from-doctl-with-an-existing-api-token-another-token-is-created-is-this-normal

**Comment by iyobo** [comment]
@metral What is the "user" parameter in this instance?
