### ISSUE TITLE
Pulumi and DO Kubernetes - tries to replace cluster after nodepool change

### ISSUE THREAD

**Issue by ninja-** [pulumi/pulumi-digitalocean#317]
It seems like when changing nodePool of digitalocean.KubernetesCluster, it's trying to "replace" the cluster...
So it tries creating new cluster and then "moving" the data, which would of course result in a big fail, while it would install the manifests into new cluster, all PVCs with data would be gone etc.
I think results could be catastrophic if someone let pulumi fully run with such change and at the end it would decide to delete the old "replaced" cluster?

Version: 2.5.0

**Comment by SnoozeFreddo** [comment]
+1

**Comment by mjeffryes** [comment]
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it?
