### ISSUE TITLE
SpacesBucket.region import warns about unexpected region

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi-digitalocean#353]
### What happened?

Reported from [community slack](https://pulumi-community.slack.com/archives/C84L4E3N1/p1673078111623329).

Trying to import a Digital Ocean Space Bucket results in a warning:
```
Diagnostics:
  digitalocean:index:SpacesBucket (pl-bucket):
    warning: One or more imported inputs failed to validate. This is almost certainly a bug in the `digitalocean` provider. The import will still proceed, but you will need to edit the generated code after copying it into your program.
    warning: digitalocean:index/spacesBucket:SpacesBucket resource 'pl-bucket' has a problem: expected region to be one of [ams3 fra1 nyc3 sfo2 sfo3 sgp1], got sfo2-zg02. Examine values at 'SpacesBucket.Region'.
```

### Steps to reproduce

Import a Space Bucket with it's region set to sfo2-zg02.

### Expected Behavior

No warning.

### Actual Behavior

See above.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
It looks to me like the [upstream provider does not currently support a region called `sfo2-zg02`](https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/digitalocean/spaces_buckets.go#L13).

This would probably need an upstream feature request.

**Comment by robbat2** [comment]
@guineveresaenger @Frassle 
Hi, I'm one of the Digitalocean Spaces Engineers. I don't know anything about Pulumi.

> Import a Space Bucket with it's region set to sfo2-zg02.
Why did the user set the region set to `sfo2-zg02` instead of plain `sfo2`?

The `-zg02` suffix is an semi-internal implementation detail should ONLY be visible in error messages so we can trace user-reported problems. E.g.
```
<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchBucket</Code><BucketName>REDACTED</BucketName><RequestId>tx000008c29423720d1a435-0063c64526-35d0c9a-sfo2b</RequestId><HostId>35d0c9a-sfo2b-sfo2-zg02</HostId></Error>
```

I don't know anywhere else the zg02 detail should be visible off the top of my head.
AWS S3 uses opaque slugs for RequestId & HostId, whereas DigitalOcean uses the underlying Ceph slugs for those fields.

Where did the user get the zg02 detail from? If it came from an error message, that's likely bad code somewhere, but certainly no code that comes to mind for me.

I would expect an S3 API GetBucketLocation call on buckets, and using that region output with the buckets in any further statements.

**Comment by Frassle** [comment]
> The -zg02 suffix is an semi-internal implementation detail should ONLY be visible in error messages so we can trace user-reported problems. E.g.

Looks like the DigitalOcean terraform provider is also surfacing these values on import:
https://pulumi-community.slack.com/archives/C84L4E3N1/p1673555486162789?thread_ts=1673078111.623329&cid=C84L4E3N1

> Oooh, the plot thickens.  I remembered that the Pulumi stuff is basically dependent on the Terraform provider, so I set up a  test Terraform environment and tried to import the bucket.  Here’s what actually got imported:
> ```
> ~/digitalocean-terraform-test ❯❯❯ terraform state show digitalocean_spaces_bucket.foobar
> # digitalocean_spaces_bucket.foobar:
> resource "digitalocean_spaces_bucket" "foobar" {
>     bucket_domain_name = "pl-bucket-prod.sfo2.digitaloceanspaces.com"
>     endpoint           = "sfo2-zg02.digitaloceanspaces.com"
>     id                 = "pl-bucket-prod"
>     name               = "pl-bucket-prod"
>     region             = "sfo2-zg02"
>     urn                = "do:space:pl-bucket-prod"
>
>     versioning {
>         enabled = false
>     }
> } ```

**Comment by robbat2** [comment]
Hi!

We found the problem, it was a slight inconsistency our side due to a bug: The `zg02` suffix leaked from GetBucketLocation in a corner case, but that's fixed now.

You should be able to close issue out.

**Comment by Frassle** [comment]
Thanks. I'll ping this to the community member who raised this and let them check.

**Comment by Frassle** [comment]
User reports this is now working, thanks @robbat2 for looking into this!
