### ISSUE TITLE
Auth issue breaks pulumi-digitalocean tests

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-digitalocean#358]
### What happened?

https://github.com/pulumi/pulumi-digitalocean/actions/runs/3909030322/jobs/6679760538#step:21:210

### Steps to reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
It looks like this issue is now fixed: https://github.com/pulumi/pulumi-digitalocean/issues/361#issuecomment-1412835508. We have PRs and tests going green.

**Comment by t0yv0** [comment]
Brilliant. Ty!
