### ISSUE TITLE
TestAccDatabaseCluster failing

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-digitalocean#372]
### What happened?

The tests is failing, possibly flaky.

Blocks updates:

- https://github.com/pulumi/pulumi-digitalocean/pull/367
- https://github.com/pulumi/pulumi-digitalocean/pull/366

Could possibly be something with the dependency updates themselves.

### Expected Behavior

Passing tests

### Steps to reproduce

See links

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
This may have been fixed by an update in the interim. Closing and we can create a new issue if we see this recur.
