### ISSUE TITLE
Can't create CDN for existing bucket

### ISSUE THREAD

**Issue by orcutt989** [pulumi/pulumi-digitalocean#406]
### What happened?

```
Diagnostics:
  digitalocean:index:Cdn (mumbainet-digitalocean-digitalocean-spaces-cdn):
    error: 1 error occurred:
    	* Error creating CDN: POST https://api.digitalocean.com/v2/cdn/endpoints: 401 (request "43fec770-c28d-4074-8ca8-840a024e1b3a") Unable to authenticate you
```

### Expected Behavior

Create CDN for existing bucket

### Steps to reproduce

Create a bucket

Try to add a CDN to it

### Output of `pulumi about`

```
CLI
Version      3.55.0
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME          VERSION
aws           5.21.1
aws           5.10.0
aws           4.38.1
digitalocean  4.19.1
docker        3.1.0
eks           0.42.7
eks           0.41.2
eks           0.33.0
kubernetes    3.22.1
kubernetes    3.20.2
nodejs        unknown

Host
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.11.0'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/xxxx
User           xxxx
Organizations  xxxx, xxxx

Dependencies:
NAME                       VERSION
@oxheadalpha/tezos-pulumi  1.1.1
@pulumi/aws                5.21.1
@pulumi/awsx               0.40.1
@pulumi/digitalocean       4.19.1
@pulumi/pulumi             3.47.1
@types/node                16.9.6
yaml                       1.10.2
@pulumi/eks                0.42.7
@pulumi/kubernetes         3.22.1
dotenv                     10.0.0
tezos-pulumi               2.0.0
````

### Additional context

I have a read/write token as a pulumi secret and I'm able to create a spaces bucket without issue, but when I try to add a CDN to it I get `Unable to authenticate you`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Hi @orcutt989 , thanks for opening this issue. Do you have the `token` attribute set in the digitalocean provider, and if not could you try that?

**Comment by orcutt989** [comment]
> Hi @orcutt989 , thanks for opening this issue. Do you have the `token` attribute set in the digitalocean provider, and if not could you try that?

I didnt create a provider. Should I? I have been able to create spaces without one.

**Comment by aq17** [comment]
@orcutt989 did you set your spaces API credentials alongside the digitalocean token? (https://www.pulumi.com/registry/packages/digitalocean/installation-configuration/#configuring-credentials)

This might be useful to reference as well: https://docs.digitalocean.com/products/spaces/how-to/manage-access/.

It looks like both may be required.

**Comment by mikhailshilkov** [comment]
@orcutt989 Were you able to resolve your issue?

**Comment by orcutt989** [comment]
Yep thanks!

**Comment by edelbalso** [comment]
I'm experiencing a similar issue with digitalocean provider. Do you folks remember what was the resolution here?
