### ISSUE TITLE
Typo: nodejs DropletSlugs consts use VPCU, should be VCPU

### ISSUE THREAD

**Issue by pjoe** [pulumi/pulumi-digitalocean#43]
Guess fixing this would break existing scripts, but it sure looks weird when reading 🤔

See e.g.: https://github.com/pulumi/pulumi-digitalocean/blob/master/sdk/nodejs/dropletSlug.ts#L30

**Comment by stack72** [comment]
d'oh! thanks for pointing this our @pjoe 

I will mark these old ones as deprecated and then create new ones in the union type! 

Paul
