### ISSUE TITLE
Error diffing firewall: `port_range` of inbound rules is required

### ISSUE THREAD

**Issue by iapetos163** [pulumi/pulumi-digitalocean#447]
### What happened?

I have a Firewall `media-firewall` that has inbound rules that grant access to the public IP of a droplet `dev-droplet`. I'm trying to deploy an update that requires replacing `dev-droplet`, but Pulumi gives this error while generating the preview:

```
  digitalocean:index:Droplet (dev-droplet):
    error: diffing urn:pulumi:application::infra-2::digitalocean:index/firewall:Firewall::media-firewall: `port_range` of inbound rules is required if protocol is `tcp` or `udp
```

My firewall definition looks like this:

```ts
  const tag = new Tag('media');
  new Firewall(`${PREFIX}-firewall`, {
    inboundRules: [
      { protocol: 'tcp', portRange: '80', sourceAddresses: allowedIps },
      { protocol: 'tcp', portRange: '443', sourceAddresses: allowedIps },
      { protocol: 'tcp', portRange: '22', sourceAddresses: allowedIps },
    ],
    outboundRules: allowAllOutbound,
    tags: [tag.name],
  });
  ```

where `allowedIps` includes the IP of `dev-droplet` (`droplet.ipv4Address`).

I get the same error even when i remove all inbound rules, or remove the firewall completely.

### Expected Behavior

The stack to proceed with replacing `dev-droplet`  before updating `media-firewall`.

### Steps to reproduce

I'm not certain how i ended up in this state, but i'm guessing that the two critical elements are 1) a firewall that depends on output from a droplet, and 2) an update that requires replacing the droplet.

### Output of `pulumi about`

```
CLI          
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
aws           5.41.0
digitalocean  4.19.4
nodejs        unknown
tailscale     0.12.1

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/brett/.local/state/fnm_multishells/30791_1677030021858/bin/node' version='v18.14.2'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iapetos163** [comment]
I was able to work around this issue by manually deleting the firewall then running `pulumi refresh`.

**Comment by AaronFriel** [comment]
Hey @iapetos163, sorry you ran into this and glad you found a workaround. If you're able to write a Pulumi program or a sequence of steps to reproduce, we'll look into this.

My hunch is that this issue lies in the upstream provider not handling unknown properties well, when `allowedIps` is an unknown value during preview. If that's the case, when you can provide steps to reproduce I think `pulumi up --skip-preview` would work, and that would confirm this hypothesis.

**Comment by AaronFriel** [comment]
Closing for now; if anyone runs into this and can reproduce, please open a new issue!
