### ISSUE TITLE
Cannot assign digitalocean.App to digitalocean.Project as digitalocean.App.urn returns Pulumi urn

### ISSUE THREAD

**Issue by varunshoor** [pulumi/pulumi-digitalocean#462]
### What happened?

Creation of a Project with a DigitalOcean App resource fails because of malformed urn.

The error on `pulumi up` is:
```
* updating urn:pulumi:prod::infra-website::digitalocean:index/project:Project::website: 1 error occurred:
* Error Updating project: Error assigning resources: POST https://api.digitalocean.com/v2/projects/f5b83018-bb5e-4e31-a505-220fd3d07d35/resources: 400 (request "da744fd1-9515-41ed-9a31-61936d06976c") resource objects must have an urn in the following format: do:resource_type:resource_id
```

Inspecting the value of App.urn shows the value as "urn:pulumi:prod::infra-website::digitalocean:index/app:App::website", while it should be something along the lines of "do:app:366601887

### Expected Behavior

The project should get created with the App as a resource. This works with Droplet but fails with App.

### Steps to reproduce

Use the following code to create a DigitalOcean App. Ensure the Container Registry has the image specified.
```
const doWebsiteApp = new digitalocean.App("website", {
  spec: {
    name: "website",
    region: "nyc",
    services: [
      {
        name: "website",
        image: {
          registryType: "DOCR",
          repository: "website",
          tag: "latest",
        },
        instanceCount: 1,
        instanceSizeSlug: "professional-xs", // doctl apps tier instance-size list
      },
    ],
  },
});

let doWebsiteProject = new digitalocean.Project("website", {
  description: "Manages the website",
  environment: "Production",
  resources: [doWebsiteApp.urn],
});
```

### Output of `pulumi about`

CLI
Version      3.76.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in nodejs: executable='/Users/varunshoor/Library/Caches/fnm_multishells/81754_1690101295336/bin/node' version='v18.15.0'

Current Stack: orgname/infra-website/prod

Found no resources associated with prod

Found no pending operations associated with prod

Backend
Name           pulumi.com
URL            https://app.pulumi.com/varunshoor
User           varunshoor
Organizations  varunshoor, orgname

Pulumi locates its logs in /var/folders/9p/vdhhpscd33g55_dw3_zjwp840000gn/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /Users/varunshoor/orgname/infra-website/src/yarn.lock or /Users/varunshoor/orgname/infra-website/src/package-lock.json

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
@varunshoor Thanks for reporting this issue! It looks like a field name clash, where `urn` here will return the Pulumi resource URN as you identified. We'll need to map the upstream provider `urn` field to `appUrn` to align with the other resource urns. Example code: https://github.com/pulumi/pulumi-digitalocean/blob/13d3b53e90ab06fc04eb0b1e822bdbaf1d55b03a/provider/resources.go#L172-L176

**Comment by varunshoor** [comment]
Thanks! That was quick!

There is also an issue in documentation for `AppSpecDomainName`, thought I would report it here rather than opening a separate issue: https://github.com/pulumi/pulumi-digitalocean/blob/13d3b53e90ab06fc04eb0b1e822bdbaf1d55b03a/sdk/java/src/main/java/com/pulumi/digitalocean/outputs/GetAppSpecDomain.java#L36C1-L42C6

The values should be `DEFAULT`, `PRIMARY` or `ALIAS`. The return value comment seems to be a result of an erroneous copy paste from other `AppSpec` objects.

**Comment by rquitales** [comment]
The PR for this fix was just merged. I'll cut a new minor release (v4.21.0) for this to pick up this change soon.

For the documentation issue, do you mind creating another issue for this. I think it may be slightly more involved with a deeper underlying issue of our codegen.
