### ISSUE TITLE
cluster.name is not the actual name

### ISSUE THREAD

**Issue by orcutt989** [pulumi/pulumi-digitalocean#466]
### What happened?

Cluster.name returns `do-cluster-####` 

This is the cluster name in the DO interface. However the actual name of the cluster in the k8s api is below and desired

### Expected Behavior

`do-region-do-cluster-####`

### Steps to reproduce

```typescript
const cluster = new digitalocean.KubernetesCluster("do-cluster", {
  region: digitalocean.Region.NYC1,
  version: "1.27.2-do.0",
  autoUpgrade: true,
  nodePool: {
    name: "default",
    size: "s-4vcpu-8gb",
    autoScale: true,
    minNodes: 1,
    maxNodes: 5
  },
});

cluster.name.apply(name=>{
  console.log(name)
})
```

### Output of `pulumi about`

pulumi about
CLI
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME          VERSION
aws           5.41.0
aws           5.31.0
aws           4.38.1
awsx          1.0.2
digitalocean  4.19.3
docker        3.6.1
eks           1.0.2
eks           0.41.2
eks           0.33.0
github        5.10.0
kubernetes    3.28.1
nodejs        unknown

Host
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.11.0'

Dependencies:
NAME                       VERSION
@pulumi/github             5.10.0
@pulumi/pulumi             3.68.0
latest-version             7.0.0
@pulumi/kubernetes         3.28.1
@types/node                20.2.3
dotenv                     16.0.3
@orgalpha/tezos-pulumi  1.1.1
@pulumi/aws                5.41.0
@pulumi/awsx               1.0.2
@pulumi/digitalocean       4.19.3
@pulumi/eks                1.0.2
tezos-pulumi               2.0.0
yaml                       2.3.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hi @orcutt989 and thanks for reporting. I believe that the cluster name output is working as intended as we want to output the cluster name defined by the DO interface. This cluster name is how we interact with the cluster via DO's APIs.

Note that the K8s API/cluster does not know its [own name or anything else that can uniquely identify it.](https://stackoverflow.com/questions/38242062/how-to-get-kubernetes-cluster-name-from-k8s-api) I believe what you're describing is the name of the cluster in a given kubeconfig, eg. the cluster name output when running `kubectl config get-contexts`. This cluster name can be renamed manually within the kubeconfig file and is a client side convenience, so it is unreliable to provide this formatting as the cluster name.

If you would like to output the kubeconfig cluster name, we suggest manually formatting it yourself after getting the DO interface cluster name.
