### ISSUE TITLE
Does it support C#?

### ISSUE THREAD

**Issue by czioutas** [pulumi/pulumi-digitalocean#49]
So as far I can see in the repo C# is not supported.
However on the [website documentation](https://www.pulumi.com/docs/intro/cloud-providers/digitalocean/setup/) it suggests it is on preview.

Indeed I found a package version of Pulumi.DigitalOcean on nuget Version="1.1.0-preview-alpha.1573818037" however this is not compatible with any of the Pulumi repos.

Not sure if I am doing something wrong or the documentation is not up to date.

Thank you!

**Comment by stack72** [comment]
Hi @czioutas 

we have a naming issue right now - but it does support it

Can you try this?

https://www.nuget.org/packages/Pulumi.Digitalocean/1.1.0-preview-

P.

**Comment by czioutas** [comment]
hey @stack72 

it worked with the 1.1.0-preview- thanks a lot!

I guess the naming issue is broader? Noticed the actual pulumi package has `undef` in the name

`<PackageReference Include="Pulumi" Version="1.6.0-preview-undef-alpha" />`

**Comment by stack72** [comment]
Yeah I am really sorry about that @czioutas 

I will bring that up with the team today and see if we can fix this up asap!

**Comment by czioutas** [comment]
cool! I will be raising a few more tickets as I am now digging into the code for digitalocean. 
Sorry :/

**Comment by stack72** [comment]
@czioutas please do :) I just noticed from your GH profile that you are in Berlin... @jen20 and I will be there speaking at Pulumi next week so if you want to talk in person, then just let us know!

**Comment by czioutas** [comment]
@stack72 next week will be tough due to some personal issues. but def interesting in the future to catch up.

**Comment by stack72** [comment]
No worries! We are based in Europe and you can find my email in GH :)
