### ISSUE TITLE
Unable to import SpacesBucket

### ISSUE THREAD

**Issue by MrSimonEmms** [pulumi/pulumi-digitalocean#50]
Hi

I'm trying to use the `import` feature on the `SpacesBucket` object.

My intended workflow is:
1. On `up`:
   - if bucket id doesn't exist, create it
   - if bucket id does exist, import that into the stack
2. On `destroy`
   - if bucket has files, don't destroy it
   - if bucket is empty, destroy it

The code I'm using is:

```
const bucket = new digitalocean.SpacesBucket(
      'my-staging-cdn',
      {
        name: 'my-staging-cdn-ebeb4c1',
        region: digitalocean.Regions.AMS3,
        acl: 'public-read',
      },
      {
        import: 'my-staging-cdn-ebeb4c1',
      },
    );
```

This results in

```
Diagnostics:
  pulumi:pulumi:Stack (my-staging-stack):
 
    error: preview failed
 
  digitalocean:index:SpacesBucket (my-staging-cdn):
    error: Preview failed: refreshing urn:pulumi:my-staging::my::digitalocean:index/spacesBucket:SpacesBucket::my-staging-cdn: error reading Spaces bucket "my-staging-cdn-ebeb4c2": RequestError: send request failed
    caused by: Head https://my-staging-cdn-ebeb4c2..digitaloceanspaces.com/: dial tcp: lookup my-staging-cdn-ebeb4c2..digitaloceanspaces.com: no such host
```

When I've created it separately, I can confirm that the result of `bucket.id.apply()...` is indeed `my-staging-cdn-ebeb4c1`. I've also tried adding `.ams3` after the ID and that does the same.

No matter what I do, I can't get the import to work - help would be very much appreciated please.

Thanks

**Comment by leezen** [comment]
In case you're still looking at this or others come across this issue, the import ID is actually of the form `<region>,<name>` so you'll want to import this as `ams3,my-staging-cdn-ebeb4c1`
