### ISSUE TITLE
DigitalOcean ReservedIp resource has a field urn that clashes with Pulumi urn

### ISSUE THREAD

**Issue by lbialy** [pulumi/pulumi-digitalocean#528]
### What happened?

While generating digitalocean package for Pulumi-scala we have ran into an issue with ReservedIp resource. Codegen for Pulumi Scala (and scala compiler too) is stricter than existing codegens and it's an error for resources to have a field conflicting with reserved Pulumi field name. In this case it's urn field of ReservedIp that's conflicting. This is probably also causing #352. I have submitted a PR #515 to fix this.

### Example

Not easy to do, but easy to check, see here https://www.pulumi.com/registry/packages/digitalocean/api-docs/reservedip/#urn_nodejs

### Output of `pulumi about`

Codegen for besom 0.2.0-snapshot so no pulumi about

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Fixed in https://github.com/pulumi/pulumi-digitalocean/pull/547
