### ISSUE TITLE
ReservedIp and ReservedIpAssignment expect dropletId as a Input<number> but Droplet outputs ID as Output<string>

### ISSUE THREAD

**Issue by varunshoor** [pulumi/pulumi-digitalocean#599]
### What happened?

The output of `id` in Droplet resource is of Output<string> forcing the use of `.apply` to pass on the ID to `ReservedIp` or `ReservedIpAssignment`

### Example

```ts
export const vpnDropletId = vpnDroplet.id.apply((id) => parseInt(id));

export const vpnReservedIp = new digitalocean.ReservedIp("vpnReservedIp", {
  dropletId: vpnDropletId,
  region: vpnDroplet.region,
});
```

Expected:

```ts
export const vpnReservedIp = new digitalocean.ReservedIp("vpnReservedIp", {
  dropletId: vpnDroplet.id,
  region: vpnDroplet.region,
});
```

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @varunshoor. This is a know issue with the provider, but fixing it is a breaking change. I have opened up #600 to track a fix.
