### ISSUE TITLE
Kubeconfig of cluster expires and breaks k8s provider

### ISSUE THREAD

**Issue by protometa** [pulumi/pulumi-digitalocean#77]
I followed [the recommended pattern for provisioning a k8s cluster and using it directly in a provider for k8s resources](https://www.digitalocean.com/community/tutorials/how-to-manage-digitalocean-and-kubernetes-infrastructure-with-pulumi). Everything works fine at first, but it seems that the kubeconfig of the cluster eventually expires and renders the provider unable to make changes and throws warnings on `pulumi up`:

    warning: configured Kubernetes cluster is unreachable: unable to load schema information from the API server: the server has asked for the client to provide credentials

I confirmed that the kubeconfig from a `pulumi stack output kubeconfig` no longer works with `kubectl`. But a new kubeconfig from `doctl k8s cluster kubeconfig show <cluster-name>` works fine, presumably because it has fresh creds.

Is there a way to make this pattern work long term? Hopefully without modifying the provider and triggering a replace on all cluster resources...

**Comment by lblackstone** [comment]
https://github.com/pulumi/examples/blob/d617a14bb933a7f54710100210eb603e9c1558ae/digitalocean-ts-k8s/index.ts#L25-L36 should fix that problem. I'll update that blog post to match.

**Comment by protometa** [comment]
That works but it floods the access token list on the digital ocean console with new tokens for every update. Would be much better if it cached a working kubeconfig somehow and only fetched a new one on expiration.

**Comment by lblackstone** [comment]
@protometa Hmm, thanks for letting me know. Would you mind opening a new issue with details on what you're seeing in the DO console so we can investigate that behavior further?

**Comment by protometa** [comment]
#78
