### ISSUE TITLE
Managed OpenSearch

### ISSUE THREAD

**Issue by ainsleyclark** [pulumi/pulumi-digitalocean#854]
Hey,

I can't see any managed OpenSearch instance config in the go package, is it possible to create one?

Thanks

**Comment by iwahbe** [comment]
Hi @ainsleyclark. Thanks for opening an issue.

The only OpenSearch related resource I could find currently for the provider is https://www.pulumi.com/registry/packages/digitalocean/api-docs/databaseopensearchconfig/.

If that's not what you are looking for, then you will need to file an issue in the upstream provider [here](https://github.com/digitalocean/terraform-provider-digitalocean/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=) (pulumi-digitalocean is generated from digitalocean/terraform-provider-digitalocean, so we have exactly the same set of resources that they do).

**Comment by ainsleyclark** [comment]
Nice one thank you, I think this is what I'm looking for.
