### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by cowwoc** [pulumi/pulumi-digitalocean#865]
### Describe what happened

Search for "PostreSQL" and replace with "PostgreSQL" across the API source code and comments :)

### Sample program

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Hey @cowwoc thanks for pointing out the typo! I've raised a PR to fix this, appreciate the attention = )

https://github.com/pulumi/pulumi-digitalocean/pull/866
