### ISSUE TITLE
spacesEndpoint should be optional in ProviderArgs

### ISSUE THREAD

**Issue by hazsetata** [pulumi/pulumi-digitalocean#94]
When updating my project from Pulumi 1.13 to 2.1 I ran into this problem: 

the ProviderArgs for DigitalOcean provider requires that I specify a value for spacesEndpoint, even when I'm not using the Spaces API. All the other parameters (including other Spaces related options like accessId / secretKey are optional). 

I also checked the Terraform provider's documentation, this parameter is marked as Optional there.

**Comment by stack72** [comment]
Hey @hazsetata 

I am going to raise an issue upstream as it seems that the schema marks this as required in TF - https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/provider.go#L29

Give me a little time here to find out

Paul
